version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.4.1
    restart: always
    container_name: es01
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/ealsticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/plugins
    hostname: elasticsearch
  kibana:
    image: kibana:8.4.1
    restart: always
    container_name: kib01
    networks:
      - elastic
    ports:
      - 5601:5601
    environment:
      - elasticsearch_url=http://elasticsearch:9200
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/data:/usr/share/kibana/data
      - ./kibana/plugins:/usr/share/kibana/plugins
    depends_on:
      - elasticsearch
    hostname: kibana
networks:
  elastic:
    driver: bridge
